# Generated by Django 4.2 on 2023-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='doj',
            field=models.DateField(null=True),
        ),
    ]
